
export const EXPONENCIAL = 'EXPONENCIAL'
export const LOGARITMICA = 'LOGARITMICA'
export const CUADRATICA = 'CUADRATICA'
export const POLINOMICA = 'POLINOMICA'
export const SENO = 'SENO'
export const EXPONENCIAL_SIMPLE = 'EXPONENCIAL_SIMPLE'
export const GAUSS = 'GAUSS'
export const EXPONENCIAL_NEGATIVA='EXPONENCIAL_NEGATIVA'